<a href="https://colab.research.google.com/github/fgsantosti/AlgoritmoseProgramacao/blob/master/Fundos_Imobiliarios_Analise_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [168]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.68)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.27.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.7.1)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)

In [169]:
from datetime import datetime
import pandas as pd 
import yfinance as yf 
import requests 
from bs4 import BeautifulSoup 
import plotly
import openpyxl

In [170]:
url = 'https://www.fundsexplorer.com.br/ranking'

In [171]:
agent = {"User-Agent":"Mozilla/5.0"}
response = requests.get(url)

soup = BeautifulSoup(response.text, 'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table), decimal='.', thousands=',')[0]
df

    Códigodo fundo                Setor  ... VacânciaFinanceira  QuantidadeAtivos
0           APTO11              Híbrido  ...                NaN                 0
1           FIVN11            Shoppings  ...                NaN                 1
2           BZLI11  Títulos e Val. Mob.  ...                NaN                 0
3           XTED11   Lajes Corporativas  ...            100,00%                 1
4           ALMI11   Lajes Corporativas  ...                NaN                 1
..             ...                  ...  ...                ...               ...
263        CXCE11B               Outros  ...                NaN                 1
264         MFAI11              Híbrido  ...                NaN                 0
265         RBVO11               Outros  ...                NaN                 0
266         CXTL11            Logística  ...                NaN                 3
267         BBRC11               Outros  ...              2,10%                20

[268 rows x 26 columns]

In [172]:
df.dtypes

Códigodo fundo              object
Setor                       object
Preço Atual                 object
Liquidez Diária            float64
Dividendo                   object
DividendYield               object
DY (3M)Acumulado            object
DY (6M)Acumulado            object
DY (12M)Acumulado           object
DY (3M)Média                object
DY (6M)Média                object
DY (12M)Média               object
DY Ano                      object
Variação Preço              object
Rentab.Período              object
Rentab.Acumulada            object
PatrimônioLíq.              object
VPA                         object
P/VPA                      float64
DYPatrimonial               object
VariaçãoPatrimonial         object
Rentab. Patr.no Período     object
Rentab. Patr.Acumulada      object
VacânciaFísica              object
VacânciaFinanceira          object
QuantidadeAtivos             int64
dtype: object

In [173]:
df.to_csv('fundos_imob.csv') #salvando dados em um arquivo .csv 
df = pd.read_csv('fundos_imob.csv') #lendo arquivo .cvs
df

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
1             1         FIVN11  ...                NaN                1
2             2         BZLI11  ...                NaN                0
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[268 rows x 27 columns]

## Retirando os caracteres especiais do DataFrame

In [174]:
df.dtypes

Unnamed: 0                   int64
Códigodo fundo              object
Setor                       object
Preço Atual                 object
Liquidez Diária            float64
Dividendo                   object
DividendYield               object
DY (3M)Acumulado            object
DY (6M)Acumulado            object
DY (12M)Acumulado           object
DY (3M)Média                object
DY (6M)Média                object
DY (12M)Média               object
DY Ano                      object
Variação Preço              object
Rentab.Período              object
Rentab.Acumulada            object
PatrimônioLíq.              object
VPA                         object
P/VPA                      float64
DYPatrimonial               object
VariaçãoPatrimonial         object
Rentab. Patr.no Período     object
Rentab. Patr.Acumulada      object
VacânciaFísica              object
VacânciaFinanceira          object
QuantidadeAtivos             int64
dtype: object

In [175]:
df.isnull().sum()

Unnamed: 0                   0
Códigodo fundo               0
Setor                        2
Preço Atual                  8
Liquidez Diária              8
Dividendo                    0
DividendYield                8
DY (3M)Acumulado             9
DY (6M)Acumulado             9
DY (12M)Acumulado            9
DY (3M)Média                 9
DY (6M)Média                 9
DY (12M)Média                9
DY Ano                      23
Variação Preço               9
Rentab.Período               9
Rentab.Acumulada             9
PatrimônioLíq.               0
VPA                          0
P/VPA                        8
DYPatrimonial               36
VariaçãoPatrimonial         36
Rentab. Patr.no Período     36
Rentab. Patr.Acumulada      36
VacânciaFísica             145
VacânciaFinanceira         240
QuantidadeAtivos             0
dtype: int64

In [176]:
df

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
1             1         FIVN11  ...                NaN                1
2             2         BZLI11  ...                NaN                0
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[268 rows x 27 columns]

## Verificando os FIIs não descontados

In [177]:
fiis_ndescontados = df[df['P/VPA'] >= 1]
fiis_ndescontados

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
0             0         APTO11  ...                NaN                0
1             1         FIVN11  ...                NaN                1
2             2         BZLI11  ...                NaN                0
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[259 rows x 27 columns]

## Verificando os FIIs descontados

In [205]:
fiis_descontados = df[df['P/VPA'] < 100]
fiis_descontados

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
1             1         FIVN11  ...                NaN                1
3             3         XTED11  ...            100,00%                1
4             4         ALMI11  ...                NaN                1
5             5         PABY11  ...                NaN                1
6             6         ORPD11  ...                NaN                0
..          ...            ...  ...                ...              ...
263         263        CXCE11B  ...                NaN                1
264         264         MFAI11  ...                NaN                0
265         265         RBVO11  ...                NaN                0
266         266         CXTL11  ...                NaN                3
267         267         BBRC11  ...              2,10%               20

[186 rows x 27 columns]

## Verificando os FIIs descontados com a Liquidez Diária de 5000 negociações diárias

In [210]:
fiis_descontados_ld5000 = fiis_descontados[fiis_descontados['Liquidez Diária']>5000]
fiis_descontados_ld5000

     Unnamed: 0 Códigodo fundo  ... VacânciaFinanceira QuantidadeAtivos
1             1         FIVN11  ...                NaN                1
8             8         QAGR11  ...                NaN               12
9             9         GGRC11  ...              0,00%               15
15           15         GSFI11  ...                NaN               10
42           42         BLMR11  ...                NaN                0
..          ...            ...  ...                ...              ...
241         241         AIEC11  ...                NaN                2
246         246         XPSF11  ...                NaN                0
251         251         KISU11  ...                NaN                0
258         258         RBGS11  ...                NaN                1
259         259         BTWR11  ...                NaN                1

[61 rows x 27 columns]

In [215]:
#fiis_descontados_ld5000['Liquidez Diária'] 
#fiis_descontados_ld5000['P/VPA']
s=fiis_descontados_ld5000.loc[:, ['Códigodo fundo','Setor','Preço Atual','DividendYield','Liquidez Diária', 'P/VPA', 'PatrimônioLíq.']]
s.sort_values(by='PatrimônioLíq.')

    Códigodo fundo                Setor  ... P/VPA       PatrimônioLíq.
65          RBRP11               Outros  ...  89.0  R$ 1.007.350.492,52
9           GGRC11            Logística  ...  86.0  R$ 1.039.797.046,13
77          RBRR11  Títulos e Val. Mob.  ...  97.0  R$ 1.052.526.047,54
79          RBRF11  Títulos e Val. Mob.  ...  89.0  R$ 1.126.170.984,40
206         GTWR11   Lajes Corporativas  ...  88.0  R$ 1.211.075.492,36
..             ...                  ...  ...   ...                  ...
259         BTWR11   Lajes Corporativas  ...  98.0     R$ 87.703.705,42
15          GSFI11            Shoppings  ...  34.0    R$ 901.702.134,45
212         SARE11              Híbrido  ...  73.0    R$ 906.186.117,12
258         RBGS11            Shoppings  ...  31.0     R$ 97.865.283,71
127         PVBI11   Lajes Corporativas  ...  92.0    R$ 998.576.404,46

[61 rows x 7 columns]

In [214]:
fiis_descontados_ld5000.to_csv('fundos_imob_filtro.csv') #salvando dados em um arquivo .csv 
#df = fiis_descontados_ld5000.read_csv('fundos_imob.csv') #lendo arquivo .cvs